### ISSUE TITLE
.NET 7.0 ASP.net website silently failing 

### ISSUE THREAD

**Issue by andysinclair** [bugsnag/bugsnag-dotnet#163] opened 2022-12-08 13:34 UTC
### Describe the bug
BugSnag does not appear to be compatible with an ASP.net .NET 7.0 website.
The code below compiles and runs with no error, but there is no error reported in the BugSnag dashboard. I can use the same code in a .NET 7.0 console application and it works as expected.

### Environment
* Bugsnag version: 3.1 (https://www.nuget.org/packages/Bugsnag/)
* .NET 7.0
* ASP.net 7.0

### Example code snippet
var bugsnag = new Bugsnag.Client(new Configuration(API_KEY));
var ex = new Exception("Test error");
bugsnag.Notify(ex);

**Comment by gareththackeray** [comment] 2022-12-09 09:59
Hi Andy.  I couldn't reproduce the issue.  I received an exception with the plan `Bugsnag` package, as you described:

```
using Bugsnag; 

var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

app.MapGet("/error", () => {
    new Bugsnag.Client(new Configuration("API-KEY")).Notify(new Exception());
    return "error sent";
});

app.Run();
```

and with our ASP.NET package `Bugsnag.AspNet.Core` (which would be our recommended approach):

```
using Bugsnag.AspNet.Core;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddBugsnag(configuration => {
     configuration.ApiKey = "API-KEY";
});

var app = builder.Build();

app.MapGet("/error", () => {throw new Exception();});

app.Run();
```

From where exactly are you calling `Notify`?

**Comment by andysinclair** [comment] 2022-12-12 15:44
Hi Gareth.
Thanks for the reply and assistance.
I changed my project to use `Bugsnag.AspNet.Core` and it is now working. I was reluctant to do this earlier as it involved updating a dependency package `Microsoft.Extensions.Options.ConfigurationExtensions` but it all seems good now.
Will now start using the product and see if/how it can meet our requirements. Thanks!

**Comment by johnkiely1** [comment] 2023-01-04 17:14
HI @andysinclair, glad to hears its working now. Going to close this out.

**Closed by johnkiely1** 2023-01-04 17:14 UTC
Labels: awaiting feedback
