### ISSUE TITLE
Bugsnag is leaving running threads

### ISSUE THREAD

**Issue by Kleiboy92** [bugsnag/bugsnag-dotnet#149] opened 2021-10-25 12:52 UTC
### Describe the bug
Bugsnag is using 
https://github.com/bugsnag/bugsnag-dotnet/blob/4bd4acbdd554b95cc92f1dd35d582627a5ebc44b/src/Bugsnag/ThreadQueueDelivery.cs#L51

which uses new Thread which is never disposed, nor can be manually disposed. 
We need to unload our app domain (restart to be more specific) and this thread is stopping us in doing so.

So please implement IDisposable which will take care of unmanaged resources

**Comment by yousif-bugsnag** [comment] 2022-02-11 12:14
Hi @Kleiboy92, 

I've been looking into this but as far as I can tell the worker thread created by the `ThreadQueueDelivery` instance would not prevent an `AppDomain` from being unloaded. 

When `AppDomain.Unload()`  is called the runtime will call `Thread.Abort()` on any running threads, and an exception is thrown if any threads cannnot be aborted, for example if the thread is running unmanaged code or is stuck in a finally block, which isn't the case here: https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unload?redirectedfrom=MSDN&view=netframework-4.7.1#remarks

In my own testing I found that when the `AppDomain` is unloaded the thread is aborted as expected, and I haven't been able to reproduce any issue with unloading an `AppDomain` in which Bugsnag is running. Are you able to provide any more details about the specific error/issue you're seeing? Were you able to determine that this is the thread preventing the app domain from unloading?

**Comment by yousif-bugsnag** [comment] 2022-02-28 09:10
Hi @Kleiboy92, I'm going to close this as we have been unable to reproduce this issue, but we'd be happy to reopen if you can provide some more details or a reproduction example. Thanks.

**Closed by yousif-bugsnag** 2022-02-28 09:10 UTC
